name: Deploy to S3 and CloudFront

on:
    push:
        branches:
            - develop
 
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ap-southeast-2

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Create .env file
              run: |
                  echo "VITE_TOSS_CLIENT_KEY=test_ck_0RnYX2w532ZPllmOPDZl3NeyqApQ" >> .env
                  echo "VITE_FASTAPI_URL=http://54.79.32.255:8000" >> .env
                  echo "VITE_BUSINESS_API_KEY=96c13bb0281d76a84b5325cce416a8ccccccc31c7737bb4d484eef01371f04a8" >> .env
                  echo "VITE_EMAILJS_SERVICE_ID=service_bhg4i6l" >> .env
                  echo "VITE_EMAILJS_TEMPLATE_ID=template_dg7jjnk" >> .env
                  echo "VITE_EMAILJS_PUBLIC_KEY=yDN0B44_FF3lz0jzk" >> .env
                  echo "VITE_API_URL=https://d15b731cpaqp76.cloudfront.net" >> .env

            - name: Install dependencies
              run: npm install

            - name: Build React app
              run: npm run build

            - name: Deploy to S3
              run: |
                  aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

            - name: Invalidate CloudFront cache
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"